name: Deploy to WordPress.org
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: Updates to calculator master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: "ci-${{ github.event.repository.name }}"